FROM jl-core:1.1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade && apt-get install -y tzdata

RUN rm /etc/localtime && echo "UTC" > /etc/timezone.
RUN dpkg-reconfigure -f noninteractive tzdata

RUN apt-get install -y python3.10 python3-pip openjdk-21-jdk git
RUN useradd lab; mkdir /home/lab
COPY stat.ipynb /home/lab
COPY statTemplate.xlsx /home/lab
RUN chown -R lab:lab /home/lab
USER lab:lab
ENV PATH=$PATH:/home/lab/.local/bin
RUN pip install jupyterlab
RUN pip install kotlin-jupyter-kernel
ENV KOTLIN_JUPYTER_JAVA_OPTS="--add-opens=java.base/java.nio=ALL-UNNAMED"
WORKDIR /home/lab
CMD jupyter-lab --ip=0.0.0.0 --JupyterApp.token='' --no-browser
